// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BOOLEAN_WILDRPC_H_
#define FLATBUFFERS_GENERATED_BOOLEAN_WILDRPC_H_

#include "flatbuffers/flatbuffers.h"

namespace WildRPC {

struct Boolean;
struct BooleanBuilder;

struct Boolean FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BooleanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct BooleanBuilder {
  typedef Boolean Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(Boolean::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit BooleanBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Boolean> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Boolean>(end);
    return o;
  }
};

inline flatbuffers::Offset<Boolean> CreateBoolean(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool value = false) {
  BooleanBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline const WildRPC::Boolean *GetBoolean(const void *buf) {
  return flatbuffers::GetRoot<WildRPC::Boolean>(buf);
}

inline const WildRPC::Boolean *GetSizePrefixedBoolean(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<WildRPC::Boolean>(buf);
}

inline bool VerifyBooleanBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<WildRPC::Boolean>(nullptr);
}

inline bool VerifySizePrefixedBooleanBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<WildRPC::Boolean>(nullptr);
}

inline void FinishBooleanBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<WildRPC::Boolean> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBooleanBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<WildRPC::Boolean> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace WildRPC

#endif  // FLATBUFFERS_GENERATED_BOOLEAN_WILDRPC_H_
