# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WBIN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GVoxelVolume(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GVoxelVolume()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGVoxelVolume(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GVoxelVolume
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GVoxelVolume
    def Columns(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from WBIN.GVoxelColumn import GVoxelColumn
            obj = GVoxelColumn()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GVoxelVolume
    def ColumnsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GVoxelVolume
    def ColumnsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def GVoxelVolumeStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddColumns(builder, columns): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(columns), 0)
def GVoxelVolumeAddColumns(builder, columns):
    """This method is deprecated. Please switch to AddColumns."""
    return AddColumns(builder, columns)
def StartColumnsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GVoxelVolumeStartColumnsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartColumnsVector(builder, numElems)
def End(builder): return builder.EndObject()
def GVoxelVolumeEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)
import WBIN.GVoxelColumn
try:
    from typing import List
except:
    pass

class GVoxelVolumeT(object):

    # GVoxelVolumeT
    def __init__(self):
        self.columns = None  # type: List[WBIN.GVoxelColumn.GVoxelColumnT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gVoxelVolume = GVoxelVolume()
        gVoxelVolume.Init(buf, pos)
        return cls.InitFromObj(gVoxelVolume)

    @classmethod
    def InitFromObj(cls, gVoxelVolume):
        x = GVoxelVolumeT()
        x._UnPack(gVoxelVolume)
        return x

    # GVoxelVolumeT
    def _UnPack(self, gVoxelVolume):
        if gVoxelVolume is None:
            return
        if not gVoxelVolume.ColumnsIsNone():
            self.columns = []
            for i in range(gVoxelVolume.ColumnsLength()):
                if gVoxelVolume.Columns(i) is None:
                    self.columns.append(None)
                else:
                    gVoxelColumn_ = WBIN.GVoxelColumn.GVoxelColumnT.InitFromObj(gVoxelVolume.Columns(i))
                    self.columns.append(gVoxelColumn_)

    # GVoxelVolumeT
    def Pack(self, builder):
        if self.columns is not None:
            columnslist = []
            for i in range(len(self.columns)):
                columnslist.append(self.columns[i].Pack(builder))
            StartColumnsVector(builder, len(self.columns))
            for i in reversed(range(len(self.columns))):
                builder.PrependUOffsetTRelative(columnslist[i])
            columns = builder.EndVector()
        Start(builder)
        if self.columns is not None:
            AddColumns(builder, columns)
        gVoxelVolume = End(builder)
        return gVoxelVolume
