# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WBIN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MeshEdges(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeshEdges()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeshEdges(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MeshEdges
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeshEdges
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from WBIN.Float3Channel import Float3Channel
            obj = Float3Channel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MeshEdges
    def SourceFileInf(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from WBIN.SourceFileInf import SourceFileInf
            obj = SourceFileInf()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def MeshEdgesStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPosition(builder, position): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def MeshEdgesAddPosition(builder, position):
    """This method is deprecated. Please switch to AddPosition."""
    return AddPosition(builder, position)
def AddSourceFileInf(builder, sourceFileInf): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceFileInf), 0)
def MeshEdgesAddSourceFileInf(builder, sourceFileInf):
    """This method is deprecated. Please switch to AddSourceFileInf."""
    return AddSourceFileInf(builder, sourceFileInf)
def End(builder): return builder.EndObject()
def MeshEdgesEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)
import WBIN.Float3Channel
import WBIN.SourceFileInf
try:
    from typing import Optional
except:
    pass

class MeshEdgesT(object):

    # MeshEdgesT
    def __init__(self):
        self.position = None  # type: Optional[WBIN.Float3Channel.Float3ChannelT]
        self.sourceFileInf = None  # type: Optional[WBIN.SourceFileInf.SourceFileInfT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        meshEdges = MeshEdges()
        meshEdges.Init(buf, pos)
        return cls.InitFromObj(meshEdges)

    @classmethod
    def InitFromObj(cls, meshEdges):
        x = MeshEdgesT()
        x._UnPack(meshEdges)
        return x

    # MeshEdgesT
    def _UnPack(self, meshEdges):
        if meshEdges is None:
            return
        if meshEdges.Position() is not None:
            self.position = WBIN.Float3Channel.Float3ChannelT.InitFromObj(meshEdges.Position())
        if meshEdges.SourceFileInf() is not None:
            self.sourceFileInf = WBIN.SourceFileInf.SourceFileInfT.InitFromObj(meshEdges.SourceFileInf())

    # MeshEdgesT
    def Pack(self, builder):
        if self.position is not None:
            position = self.position.Pack(builder)
        if self.sourceFileInf is not None:
            sourceFileInf = self.sourceFileInf.Pack(builder)
        Start(builder)
        if self.position is not None:
            AddPosition(builder, position)
        if self.sourceFileInf is not None:
            AddSourceFileInf(builder, sourceFileInf)
        meshEdges = End(builder)
        return meshEdges
