# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WBIN

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Phys(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPhys(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Phys()
        x.Init(buf, n + offset)
        return x

    # Phys
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Phys
    def Aabb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from WBIN.AABB import AABB
            obj = AABB()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Phys
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from WBIN.Float3Channel import Float3Channel
            obj = Float3Channel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Phys
    def Materials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Phys
    def MaterialsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Phys
    def MaterialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Phys
    def MaterialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Phys
    def Skin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from WBIN.Skin import Skin
            obj = Skin()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Phys
    def SourceFileInf(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from WBIN.SourceFileInf import SourceFileInf
            obj = SourceFileInf()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PhysStart(builder): builder.StartObject(5)
def PhysAddAabb(builder, aabb): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(aabb), 0)
def PhysAddPosition(builder, position): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def PhysAddMaterials(builder, materials): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(materials), 0)
def PhysStartMaterialsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PhysAddSkin(builder, skin): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(skin), 0)
def PhysAddSourceFileInf(builder, sourceFileInf): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(sourceFileInf), 0)
def PhysEnd(builder): return builder.EndObject()

import WBIN.AABB
import WBIN.Float3Channel
import WBIN.Skin
import WBIN.SourceFileInf
try:
    from typing import List, Optional
except:
    pass

class PhysT(object):

    # PhysT
    def __init__(self):
        self.aabb = None  # type: Optional[WBIN.AABB.AABBT]
        self.position = None  # type: Optional[WBIN.Float3Channel.Float3ChannelT]
        self.materials = None  # type: List[int]
        self.skin = None  # type: Optional[WBIN.Skin.SkinT]
        self.sourceFileInf = None  # type: Optional[WBIN.SourceFileInf.SourceFileInfT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        phys = Phys()
        phys.Init(buf, pos)
        return cls.InitFromObj(phys)

    @classmethod
    def InitFromObj(cls, phys):
        x = PhysT()
        x._UnPack(phys)
        return x

    # PhysT
    def _UnPack(self, phys):
        if phys is None:
            return
        if phys.Aabb() is not None:
            self.aabb = WBIN.AABB.AABBT.InitFromObj(phys.Aabb())
        if phys.Position() is not None:
            self.position = WBIN.Float3Channel.Float3ChannelT.InitFromObj(phys.Position())
        if not phys.MaterialsIsNone():
            if np is None:
                self.materials = []
                for i in range(phys.MaterialsLength()):
                    self.materials.append(phys.Materials(i))
            else:
                self.materials = phys.MaterialsAsNumpy()
        if phys.Skin() is not None:
            self.skin = WBIN.Skin.SkinT.InitFromObj(phys.Skin())
        if phys.SourceFileInf() is not None:
            self.sourceFileInf = WBIN.SourceFileInf.SourceFileInfT.InitFromObj(phys.SourceFileInf())

    # PhysT
    def Pack(self, builder):
        if self.position is not None:
            position = self.position.Pack(builder)
        if self.materials is not None:
            if np is not None and type(self.materials) is np.ndarray:
                materials = builder.CreateNumpyVector(self.materials)
            else:
                PhysStartMaterialsVector(builder, len(self.materials))
                for i in reversed(range(len(self.materials))):
                    builder.PrependUint32(self.materials[i])
                materials = builder.EndVector(len(self.materials))
        if self.skin is not None:
            skin = self.skin.Pack(builder)
        if self.sourceFileInf is not None:
            sourceFileInf = self.sourceFileInf.Pack(builder)
        PhysStart(builder)
        if self.aabb is not None:
            aabb = self.aabb.Pack(builder)
            PhysAddAabb(builder, aabb)
        if self.position is not None:
            PhysAddPosition(builder, position)
        if self.materials is not None:
            PhysAddMaterials(builder, materials)
        if self.skin is not None:
            PhysAddSkin(builder, skin)
        if self.sourceFileInf is not None:
            PhysAddSourceFileInf(builder, sourceFileInf)
        phys = PhysEnd(builder)
        return phys
