# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WBIN

class SDFValues(object):
    NONE = 0
    shortval = 1
    floatval = 2
    doubleval = 3


def SDFValuesCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == SDFValues().shortval:
        import WBIN.shortval
        return WBIN.shortval.shortvalT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SDFValues().floatval:
        import WBIN.floatval
        return WBIN.floatval.floatvalT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SDFValues().doubleval:
        import WBIN.doubleval
        return WBIN.doubleval.doublevalT.InitFromBuf(table.Bytes, table.Pos)
    return None
