# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WildRPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Boolean(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBoolean(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Boolean()
        x.Init(buf, n + offset)
        return x

    # Boolean
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Boolean
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BooleanStart(builder): builder.StartObject(1)
def BooleanAddValue(builder, value): builder.PrependBoolSlot(0, value, 0)
def BooleanEnd(builder): return builder.EndObject()
