# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WildRPC

class Type(object):
    UInt3 = 1
    Vector3 = 2
    Vector2 = 3
    Quat = 4
    Position = 5
    Float = 6
    Integer = 7
    Boolean = 8
    Color = 9

