# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WildRPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Quat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Quat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Quat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Quat
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Quat
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Quat
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Quat
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(4)
def QuatStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def QuatAddX(builder, x):
    """This method is deprecated. Please switch to AddX."""
    return AddX(builder, x)
def AddY(builder, y): builder.PrependFloat32Slot(1, y, 0.0)
def QuatAddY(builder, y):
    """This method is deprecated. Please switch to AddY."""
    return AddY(builder, y)
def AddZ(builder, z): builder.PrependFloat32Slot(2, z, 0.0)
def QuatAddZ(builder, z):
    """This method is deprecated. Please switch to AddZ."""
    return AddZ(builder, z)
def AddW(builder, w): builder.PrependFloat32Slot(3, w, 0.0)
def QuatAddW(builder, w):
    """This method is deprecated. Please switch to AddW."""
    return AddW(builder, w)
def End(builder): return builder.EndObject()
def QuatEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)

class QuatT(object):

    # QuatT
    def __init__(self):
        self.x = 0.0  # type: float
        self.y = 0.0  # type: float
        self.z = 0.0  # type: float
        self.w = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        quat = Quat()
        quat.Init(buf, pos)
        return cls.InitFromObj(quat)

    @classmethod
    def InitFromObj(cls, quat):
        x = QuatT()
        x._UnPack(quat)
        return x

    # QuatT
    def _UnPack(self, quat):
        if quat is None:
            return
        self.x = quat.X()
        self.y = quat.Y()
        self.z = quat.Z()
        self.w = quat.W()

    # QuatT
    def Pack(self, builder):
        Start(builder)
        AddX(builder, self.x)
        AddY(builder, self.y)
        AddZ(builder, self.z)
        AddW(builder, self.w)
        quat = End(builder)
        return quat
