// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WAREAMESH_WBIN_H_
#define FLATBUFFERS_GENERATED_WAREAMESH_WBIN_H_

#include "flatbuffers/flatbuffers.h"

#include "wbin_generated.h"

namespace WBIN {

struct AreaMesh;
struct AreaMeshBuilder;
struct AreaMeshT;

struct AreaMeshT : public flatbuffers::NativeTable {
  typedef AreaMesh TableType;
  std::unique_ptr<WBIN::Float3ChannelT> position{};
};

struct AreaMesh FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AreaMeshT NativeTableType;
  typedef AreaMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4
  };
  const WBIN::Float3Channel *position() const {
    return GetPointer<const WBIN::Float3Channel *>(VT_POSITION);
  }
  WBIN::Float3Channel *mutable_position() {
    return GetPointer<WBIN::Float3Channel *>(VT_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           verifier.EndTable();
  }
  AreaMeshT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AreaMeshT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<AreaMesh> Pack(flatbuffers::FlatBufferBuilder &_fbb, const AreaMeshT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AreaMeshBuilder {
  typedef AreaMesh Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_position(flatbuffers::Offset<WBIN::Float3Channel> position) {
    fbb_.AddOffset(AreaMesh::VT_POSITION, position);
  }
  explicit AreaMeshBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AreaMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AreaMesh>(end);
    fbb_.Required(o, AreaMesh::VT_POSITION);
    return o;
  }
};

inline flatbuffers::Offset<AreaMesh> CreateAreaMesh(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<WBIN::Float3Channel> position = 0) {
  AreaMeshBuilder builder_(_fbb);
  builder_.add_position(position);
  return builder_.Finish();
}

flatbuffers::Offset<AreaMesh> CreateAreaMesh(flatbuffers::FlatBufferBuilder &_fbb, const AreaMeshT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline AreaMeshT *AreaMesh::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AreaMeshT>(new AreaMeshT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AreaMesh::UnPackTo(AreaMeshT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<WBIN::Float3ChannelT>(_e->UnPack(_resolver)); }
}

inline flatbuffers::Offset<AreaMesh> AreaMesh::Pack(flatbuffers::FlatBufferBuilder &_fbb, const AreaMeshT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAreaMesh(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<AreaMesh> CreateAreaMesh(flatbuffers::FlatBufferBuilder &_fbb, const AreaMeshT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const AreaMeshT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _position = _o->position ? CreateFloat3Channel(_fbb, _o->position.get(), _rehasher) : 0;
  return WBIN::CreateAreaMesh(
      _fbb,
      _position);
}

inline const WBIN::AreaMesh *GetAreaMesh(const void *buf) {
  return flatbuffers::GetRoot<WBIN::AreaMesh>(buf);
}

inline const WBIN::AreaMesh *GetSizePrefixedAreaMesh(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<WBIN::AreaMesh>(buf);
}

inline AreaMesh *GetMutableAreaMesh(void *buf) {
  return flatbuffers::GetMutableRoot<AreaMesh>(buf);
}

inline bool VerifyAreaMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<WBIN::AreaMesh>(nullptr);
}

inline bool VerifySizePrefixedAreaMeshBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<WBIN::AreaMesh>(nullptr);
}

inline void FinishAreaMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<WBIN::AreaMesh> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAreaMeshBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<WBIN::AreaMesh> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<WBIN::AreaMeshT> UnPackAreaMesh(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<WBIN::AreaMeshT>(GetAreaMesh(buf)->UnPack(res));
}

inline std::unique_ptr<WBIN::AreaMeshT> UnPackSizePrefixedAreaMesh(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<WBIN::AreaMeshT>(GetSizePrefixedAreaMesh(buf)->UnPack(res));
}

}  // namespace WBIN

#endif  // FLATBUFFERS_GENERATED_WAREAMESH_WBIN_H_
