// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WildRpcApiGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PythonApiGenerator : BaseApiGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 6 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	string typeToRpcEnum(ReflectionMethod.Parameter param)
	{
		return "RpcType." + param.elementType + (param.isArray ? "Array" : "");
	}

	string typeToPython(ReflectionMethod.Parameter param)
	{
		return param.elementType switch
		{
			{ } when isEnum(param) => "_" + param.elementTypeName,
			ElementType.Invalid => "Any",
			ElementType.Boolean => "bool",
			ElementType.Integer => "int",
			ElementType.Float => "float",
			ElementType.String => "str",
			_ => param.elementType.ToString()
		};
	}

	static string cleanupName(string name)
	{
		return name.Replace("::", "_");
	}

	string cleanupParam(ReflectionMethod.Parameter param)
	{
		if (isEnum(param))
		{
			return $"{param.name}.value";
		}
		return param.name;
	}


	string joinInputCalls(ReflectionMethod method)
	{
		var joined = method.inputs.Select(cleanupParam).join(cleanupName);
		return method.inputs.Length switch
		{
			0 => "None",
			1 => $"({joined},)", // trailing comma for single-argument tuples
			_ => $"({joined})",
		};
	}

	string joinReturnTypes(ReflectionMethod method)
	{
		return method.outputs.Length switch
		{
			0 => "None",
			1 => method.outputs.join(typeToPython),
			_ => $"Tuple[{method.outputs.join(typeToPython)}]",
		};
	}

            
            #line default
            #line hidden
            this.Write(@"# -*- coding: future_fstrings -*-
""""""
RPC bindings for the Wild game.

THIS FILE WAS AUTOGENERATED.
""""""
from __future__ import print_function, absolute_import
from builtins import super

from .rpc_api import RpcApi, RpcMethod
from .rpc_types import RpcType, Vector3, Position, Quat, Color
from typing import Tuple, Any


class RpcApiWild(RpcApi):
	def __init__(self, address=(""127.0.0.1"", 9387)):  # type: (Tuple[str, int]) -> None
		super().__init__(address)
");
            
            #line 79 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	// manager instances
	foreach (var @class in reflectionDb.classes)
	{
		var memberName = @class.name.Replace("Manager", "").ToLowerFirstLetter();
		memberName = memberName.Replace("rPC", "rpc");

            
            #line default
            #line hidden
            this.Write("\t\tself.");
            
            #line 86 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 86 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@class.name));
            
            #line default
            #line hidden
            this.Write("(self)\r\n");
            
            #line 87 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 92 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	// manager classes
	foreach (var @class in reflectionDb.classes)
	{

            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 97 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@class.name));
            
            #line default
            #line hidden
            this.Write("(object):\r\n\tdef __init__(self, api):  # type: (RpcApi) -> None\r\n");
            
            #line 99 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		// manager method signatures
		foreach (var method in @class.methods)
		{

            
            #line default
            #line hidden
            this.Write("\t\tself._");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.name));
            
            #line default
            #line hidden
            this.Write(" = RpcMethod(api, \"");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@class.name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.name));
            
            #line default
            #line hidden
            this.Write("\", [");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.inputs.join(typeToRpcEnum)));
            
            #line default
            #line hidden
            this.Write("], [");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.outputs.join(typeToRpcEnum)));
            
            #line default
            #line hidden
            this.Write("], thread_safe=");
            
            #line 104 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.threadSafe ? "True" : "False"));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 105 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 109 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		// manager method wrappers
		foreach (var method in @class.methods)
		{
			var inputNames = method.inputs.joinNames(cleanupName);
			if (inputNames != "") inputNames = ", " + inputNames;
			var inputCalls = joinInputCalls(method);

            
            #line default
            #line hidden
            this.Write("\tdef ");
            
            #line 117 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.niceName()));
            
            #line default
            #line hidden
            this.Write("(self");
            
            #line 117 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputNames));
            
            #line default
            #line hidden
            this.Write("):  # type: (");
            
            #line 117 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.inputs.join(typeToPython)));
            
            #line default
            #line hidden
            this.Write(") -> ");
            
            #line 117 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(joinReturnTypes(method)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 118 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

			if (method.outputs.Length == 0)
			{

            
            #line default
            #line hidden
            this.Write("\t\tself._");
            
            #line 122 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.name));
            
            #line default
            #line hidden
            this.Write(".invoke(params=");
            
            #line 122 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputCalls));
            
            #line default
            #line hidden
            this.Write(", results=None, throw_on_error=True)\r\n");
            
            #line 123 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t_results = self._");
            
            #line 128 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.name));
            
            #line default
            #line hidden
            this.Write(".invoke(params=");
            
            #line 128 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(inputCalls));
            
            #line default
            #line hidden
            this.Write(", results=[], throw_on_error=True)\r\n");
            
            #line 129 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

				// some parameters need custom converters
				for (int i = 0; i < method.outputs.Length; i++)
				{
					var output = method.outputs[i];
					if (!isEnum(output)) continue;
					// TODO: handle conversion of array elements

            
            #line default
            #line hidden
            this.Write("\t\t_results[");
            
            #line 137 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("] = _");
            
            #line 137 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(output.elementTypeName));
            
            #line default
            #line hidden
            this.Write("(_results[");
            
            #line 137 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("])\r\n");
            
            #line 138 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

				}

            
            #line default
            #line hidden
            this.Write("\t\treturn _results");
            
            #line 141 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.outputs.Length == 1 ? "[0]" : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 142 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 146 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		}

		// expose get/set method pairs as Python properties
		var properties = @class.findProperties();
		foreach (var property in properties)
		{
			if (property.getter.outputs.Length > 1)
			{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 156 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.name));
            
            #line default
            #line hidden
            this.Write(" = property(");
            
            #line 156 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.getter.niceName()));
            
            #line default
            #line hidden
            this.Write(", lambda self, *args: self.");
            
            #line 156 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.setter.niceName()));
            
            #line default
            #line hidden
            this.Write("(*args))  # type: ");
            
            #line 156 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(joinReturnTypes(property.getter)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 157 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 162 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.name));
            
            #line default
            #line hidden
            this.Write(" = property(");
            
            #line 162 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.getter.niceName()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 162 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.setter.niceName()));
            
            #line default
            #line hidden
            this.Write(")  # type: ");
            
            #line 162 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(joinReturnTypes(property.getter)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 163 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

			}
		}

		// add padding if necessary
		if (properties.Any())
			WriteLine("");

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 172 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("#\r\n# Enums\r\n# NOTE: some property have the same name as their enum type, which me" +
                    "sses up autocomplete, so we use an _alias.\r\n#\r\nfrom enum import IntEnum\r\n\r\n");
            
            #line 181 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	foreach (var @enum in reflectionDb.enums)
	{

            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 185 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@enum.name));
            
            #line default
            #line hidden
            this.Write("(IntEnum):\r\n");
            
            #line 186 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		foreach (var (value, name) in @enum.values.Zip(@enum.names))
		{
			if (name.EndsWith("_COUNT")) continue;

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 191 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 191 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 192 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("_");
            
            #line 195 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@enum.name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 195 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@enum.name));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            
            #line 198 "D:\WildCode\WildShared\WildRpcApiGenerator\Generators\PythonApiGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\napi = RpcApiWild()\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
