---
name: CMake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        BUILD_TYPE:
          - Debug
          - Release
        cppstd:
          - 17
          - 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}
          -DCMAKE_CXX_STANDARD=${{matrix.cppstd}}
      - name: Build EntLibAPIGenerator
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}
          --target EntLibAPIGenerator
      - name: Build UpdateSchemas
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}
          --target UpdateSchemas
      - name: Merge UnitTest Schemas
        run: \"build/Release/UpdateSchemas\" -o build/Schemas -e
          DemoSchemas/EditionComponents.json,DemoSchemas/Scene-schema.json -r
          DemoSchemas/RuntimeComponents.json
      - name: Generate EntGen API
        run: \"build/Release/EntLibAPIGenerator\" -s build/Schemas -d build/EntGen -r
          EntLibAPIGenerator/resources
      - name: Build Unit tests
        run: cmake --build build --config Release --target TestEntityDLL
      - name: Run Unit tests
        working-directory: ${{github.workspace}}/Test
        run: ../build/Release/TestEntityDLL
